### ISSUE TITLE
Quickstart AOT buid not working

### ISSUE THREAD

**Issue by imVinayPandya** [Teradata/vantage-ui-template#41]
i have clone quickstart repo -> npm install -> ng build --prod --aot and i got following error

```
ERROR in ./~/@covalent/core/index.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (/home/vinay/covalent-quickstart/node_modules/typescript/lib/typescript.js:6635:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (/home/vinay/covalent-quickstart/node_modules/typescript/lib/typescript.js:78683:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (/home/vinay/covalent-quickstart/node_modules/typescript/lib/typescript.js:78704:77)
    at refactor.findAstNodes.filter (/home/vinay/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:135:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (/home/vinay/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:134:14)
    at Array.forEach (native)
    at _removeDecorators (/home/vinay/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:125:10)
    at Promise.resolve.then (/home/vinay/covalent-quickstart/node_modules/@ngtools/webpack/src/loader.js:295:33)
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 68:0-49
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by natejgardner** [comment]
Does `./src/main.ts` exist for you?
